<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>MobileControlHub.WebApi</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Common" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MobileControlHub.Domain\MobileControlHub.Domain.csproj" />
    <ProjectReference Include="..\MobileControlHub.Infrastructure\MobileControlHub.Infrastructure.csproj" />
  </ItemGroup>

</Project>
